version: "3.8"

services:
  frontend-service:
    build: ./frontend3
    depends_on:
      backend-service:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - front-network

  backend-service:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    networks:
      - back-network
      - front-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 20
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_database:3306/mysql_database
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  database:
    build: ./database
    hostname: mysql_database
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_database
    networks:
      - back-network
    command:
      - --mysql-native-password=ON
      - --transaction-isolation=READ-COMMITTED
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 20
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  back-network:
    driver: bridge
  front-network:
    driver: bridge
