services:
  frontend-service:
    build: ./frontend
    depends_on:
      backend-service:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - front-network

  backend-service:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    networks:
      - back-network
      - front-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 20
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - BACKEND_JWT_SECRET=${BACKEND_JWT_SECRET}
      - BACKEND_JWT_TOKEN_VALID_TIME=${BACKEND_JWT_TOKEN_VALID_TIME:-36000}
      - BACKEND_VERIFICATION_CODE_EXPIRATION_MINUTES=${BACKEND_VERIFICATION_CODE_EXPIRATION_MINUTES:-60}
      - BACKEND_EMAIL_USERNAME=${BACKEND_EMAIL_USERNAME}
      - BACKEND_EMAIL_PASSWORD=${BACKEND_EMAIL_PASSWORD}
      - BACKEND_EMAIL_HOST=${BACKEND_EMAIL_HOST:-smtp.gmail.com}
      - BACKEND_EMAIL_PORT=${BACKEND_EMAIL_PORT:-587}
      - BACKEND_EMAIL_PROTOCOL=${BACKEND_EMAIL_PROTOCOL:-smtp}
      - BACKEND_EMAIL_TRUST=${BACKEND_EMAIL_TRUST:-smtp.gmail.com}

  database:
    build: ./database
    hostname: mysql_database
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_database
    networks:
      - back-network
    command:
      - --mysql-native-password=ON
      - --transaction-isolation=READ-COMMITTED
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 20
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  back-network:
    driver: bridge
  front-network:
    driver: bridge
